# Generated by Django 3.0.5 on 2020-04-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendomaticapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
